package urbanjungletech.hardwareservice.addition;

import urbanjungletech.hardwareservice.model.HardwareControllerGroup;

public interface HardwareControllerGroupAdditionService extends AdditionService<HardwareControllerGroup>{
}
