### Crate a basic hardware controller

POST http://localhost:8081/hardwarecontroller/
Content-Type: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.13 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Accept: application/json
Content-Length: 328

{
  "type":"mqtt",
  "configuration":{
    "serialNumber":"5454364324",
    "server":"tcp://mqtt:1883",
    "responseQueue":"HardwareServer",
    "requestQueue":"1235ToMicro"
  }
}


> {%
    client.global.set("controllerId", response.body.id);
%}

### Create a temperature sensor on port 2 of type 18B20

POST http://localhost:8081/hardwarecontroller/{{controllerId}}/sensor
Content-Type: application/json
Connection: Keep-Alive
accept: application/json

{
  "name":"temperature sensor 1",
  "port": "2",
  "configuration": {
    "sensor_type": "18B20"
  }
}

> {%
    client.global.set("temperatureSensorId", response.body.id);
%}

### Read the temperature sensor

GET http://localhost:8081/sensor/{{temperatureSensorId}}/reading
Content-Type: application/json
Connection: Keep-Alive
accept: application/json


### Create the green light on port 15

POST http://localhost:8081/hardwarecontroller/{{controllerId}}/hardware
Content-Type: application/json
Connection: Keep-Alive
accept: application/json

{
  "name":"green light",
  "type":"light",
  "port": "15",
  "desiredState": {
    "state": "ON",
    "level": 100
  }
}

> {%
    client.global.set("greenLightId", response.body.id);
%}

### Create the blue light on port 18

POST http://localhost:8081/hardwarecontroller/{{controllerId}}/hardware
Content-Type: application/json
Connection: Keep-Alive
accept: application/json

{
  "name":"blue light",
  "type":"light",
  "port": "18",
  "desiredState": {
    "state": "ON",
    "level": 100
  }
}

> {%
    client.global.set("blueLightId", response.body.id);
%}

### create the orange light on port 19

POST http://localhost:8081/hardwarecontroller/{{controllerId}}/hardware
Content-Type: application/json
Connection: Keep-Alive
accept: application/json

{
  "name":"orange light",
  "type":"light",
  "port": "19",
  "desiredState": {
    "state": "ON",
    "level": 100
  }
}

### create the red light on port 21

POST http://localhost:8081/hardwarecontroller/{{controllerId}}/hardware
Content-Type: application/json
Connection: Keep-Alive
accept: application/json

{
  "name":"red light",
  "type":"light",
  "port": "21",
  "desiredState": {
    "state": "ON",
    "level": 100
  }
}

### Create a hardware timer which will turn the green light on and off every 3 seconds

POST http://localhost:8081/hardware/{{greenLightId}}/timer
Content-Type: application/json
Connection: Keep-Alive

{
  "name":"timer 1",
  "onLevel": 100,
  "onCronString": "*/3 * * * * ?",
  "offCronString": "*/3 * * * * ?"
}

> {%
    client.global.set("greenLightTimerId", response.body.id);
%}

### delete the hardware timer

#DELETE http://localhost:8081/timer/{{greenLightTimerId}}
