### Crate a basic hardware controller

POST http://localhost:8081/hardwarecontroller/
Content-Type: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.13 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Accept: application/json
Content-Length: 328

{
  "type":"mqtt",
  "hardware": [
    {
      "name":"lights 3",
      "port":1,
      "type":"lights",
      "configuration": {
        "hello": "world"
      }
    }
  ],
  "configuration":{
    "serialNumber":"1234",
    "server":"tcp://mqtt:1883",
    "responseQueue":"HardwareServer",
    "requestQueue":"1235ToMicro"
  }
}


> {%
    client.global.set("controllerId", response.body.id);
%}

### Get the hardware controller

GET http://localhost:8081/hardwarecontroller/{{controllerId}}

> {%
       client.global.set("hardwareId", response.body.hardware[0].id);
 %}

### Create a hardware timer which will turn the hardware on every 3 seconds

POST http://localhost:8081/hardware/{{hardwareId}}/timer
Content-Type: application/json
Connection: Keep-Alive

{
  "name":"timer 1",
  "onLevel": 100,
  "onCronString": "*/3 * * * * ?",
  "offCronString": "*/3 * * * * ?"
}

> {%
    client.global.set("timerId", response.body.id);
%}

### delete the hardware timer

DELETE http://localhost:8081/timer/{{timerId}}
