spring:
  application:
    name: hardware-service
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:file:~/db/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  sleuth:
    quartz:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  http2:
    enabled: true
  port: 8081
logging:
  level:
    root: INFO
    frentz.daniel: DEBUG
    org.hibernate.SQL: INFO
  mqtt:
    level: INFO
local:
  mqtt:
    enabled: true
    port: 1883
    host: localhost
    logAll: true
scheduling:
  distribution-strategy: local
development:
  mqtt:
    client:
      enabled: true
      serialNumber: "1234"
      callbacks:
        - "frentz.daniel.hardwareservice.config.mqtt.mockclient.SensorReadingCallback" : "ReadSensor"
        - "frentz.daniel.hardwareservice.config.mqtt.mockclient.StateChangeCallback" : "StateChange"
entity:
  names:
    frentz.daniel.hardwareservice.entity.HardwareControllerEntity: Hardware Controller
    frentz.daniel.hardwareservice.entity.SensorEntity: Sensor
    frentz.daniel.hardwareservice.entity.HardwareEntity: Hardware
    frentz.daniel.hardwareservice.entity.TimerEntity: Timer

rpc:
  methods:
    "frentz.daniel.hardwareservice.jsonrpc.method.ConfirmHardwareState": "ConfirmHardwareState"
    "frentz.daniel.hardwareservice.jsonrpc.method.DeregisterHardware": "DeregisterHardware"
    "frentz.daniel.hardwareservice.jsonrpc.method.DeregisterSensor": "DeregisterSensor"
    "frentz.daniel.hardwareservice.jsonrpc.method.GetInitialState": "GetInitialState"
    "frentz.daniel.hardwareservice.jsonrpc.method.RegisterHardware": "RegisterHardware"
    "frentz.daniel.hardwareservice.jsonrpc.method.RegisterHardwareController": "RegisterHardwareController"
    "frentz.daniel.hardwareservice.jsonrpc.method.RegisterSensor": "RegisterSensor"


mqtt:
  server: tcp://localhost:1883
  queue: HardwareServer
  listeners:
    - listener: frentz.daniel.hardwareservice.config.mqtt.mockclient
      topic: 1234ToMicrocontroller
    - listener: frentz.daniel.hardwareservice.config.mqtt.listener
      topic: FromMicrocontroller
management:
  endpoints:
    web:
      exposure:
        include: metrics
