spring:
  application:
    name: hardware-service
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:file:~/db/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  sleuth:
    quartz:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: test
server:
  http2:
    enabled: true
  port: 8081
logging:
  level:
    root: INFO
    urbanjungletech: DEBUG
    org.hibernate.SQL: INFO
  mqtt:
    level: INFO
local:
  mqtt:
    enabled: false
    port: 1883
    host: localhost
    logAll: true
scheduling:
  distribution-strategy: local
development:
  mqtt:
    client:
      enabled: false
      serialNumber: "1234"
      callbacks:
        urbanjungletech.hardwareservice.config.mqtt.mockclient.SensorReadingCallback : ReadSensor
        urbanjungletech.hardwareservice.config.mqtt.mockclient.StateChangeCallback : StateChange
        urbanjungletech.hardwareservice.config.mqtt.mockclient.RegisterHardwareCallback: RegisterHardware
entity:
  names:
    urbanjungletech.hardwareservice.entity.HardwareControllerEntity: Hardware Controller
    urbanjungletech.hardwareservice.entity.SensorEntity: Sensor
    urbanjungletech.hardwareservice.entity.HardwareEntity: Hardware
    urbanjungletech.hardwareservice.entity.TimerEntity: Timer
    urbanjungletech.hardwareservice.entity.ScheduledSensorReadingEntity: Scheduled Sensor Reading
    urbanjungletech.hardwareservice.entity.HardwareStateEntity: Hardware State
    urbanjungletech.hardwareservice.action.entity.ActionEntity: Action
    urbanjungletech.hardwareservice.entity.SensorReadingAlertEntity: Sensor Reading Alert
    urbanjungletech.hardwareservice.entity.HardwareControllerGroupEntity: Hardware Controller Group

mqtt-rpc:
  uri: tcp://mqtt:1883
  queue: HardwareServer

management:
  endpoints:
    web:
      exposure:
        include: metrics
